### ISSUE TITLE
18 videos?

### ISSUE THREAD

**Issue by clankie83** [n0l3r/tiktok-downloader#1]
Hi, it only finds 18 videos but I have over 600...

**Comment by n0l3r** [comment]
hi, you can copy the 18 video links and then download them manually, I'll make them for mass download with link

**Comment by clankie83** [comment]
I'm sorry but I have no idea what you mean. Do you mean to say that you can't bulk DL with your tool? Because single DL is very easy already with services like sstok.io...

**Comment by n0l3r** [comment]
Sorry I misunderstood what you said. Would you like to contribute to this project? you can do a pull request if so. But if not, I'll try to fix it

**Comment by clankie83** [comment]
I wish I had your skills but sadly I don't! I will try a bulk download from
another network, thank you for letting me know :-)

**Comment by n0l3r** [comment]
> I wish I had your skills but sadly I don't! I will try a bulk download from another network, thank you for letting me know :-)

I've solved this problem, you can try again in 15 minutes

**Comment by n0l3r** [comment]
@clankie83 please try the latest program, give your opinion about the program. if this problem has been solved, you can close this issue

**Comment by n0l3r** [comment]
thank u

**Comment by clankie83** [comment]
Thank you!  I have tried it twice just now and I still get 18 videos found and downloaded...

**Comment by n0l3r** [comment]
can you take a screenshot/video while running the program? post here or dm me on instagram

**Comment by n0l3r** [comment]
my instagram @yaelahfal_

**Comment by n0l3r** [comment]
its work 
![image](https://user-images.githubusercontent.com/71002775/167184155-5356cd80-b669-4e84-b1a2-94628f299ff1.png)

**Comment by n0l3r** [comment]
proccess download 525 videos
![image](https://user-images.githubusercontent.com/71002775/167184447-50fdd867-a357-46d8-8fbd-4918c7950f06.png)

**Comment by clankie83** [comment]
There you g
<img width="940" alt="ca" src="https://user-images.githubusercontent.com/103049507/167194550-de2f10da-963e-43b1-bd87-cf93483295c5.png">
o

**Comment by n0l3r** [comment]
please re-download the repository, then your code will be updated

**Comment by n0l3r** [comment]
please download and run npm install in your terminal

**Comment by n0l3r** [comment]
true

**Comment by n0l3r** [comment]
> its work 
> 
> ![image](https://user-images.githubusercontent.com/71002775/167184155-5356cd80-b669-4e84-b1a2-94628f299ff1.png)
> 
> 

this is a sample image when the program tries to get all the existing video links

**Comment by clankie83** [comment]
in terminal, I paste:

git clone https://github.com/n0l3r/tiktok-downloader.git
cd tiktok-downloader
npm i
node index

then follow the instructions.

**Comment by n0l3r** [comment]
First delete the existing tiktok-downloader folder. and make sure you enter the correct directory

**Comment by clankie83** [comment]
I deleted and downloaded again then ran:
git clone https://github.com/n0l3r/tiktok-downloader.git
cd "C:\Users\user7\tiktok-downloader-main"
npm i
node index

and got: 
<img width="303" alt="ca2" src="https://user-images.githubusercontent.com/103049507/167237767-5cae9af0-8005-4c0d-9f4e-b11ed7014450.png">

**Comment by n0l3r** [comment]
can you send the username?

**Comment by clankie83** [comment]
sent on insta

**Comment by n0l3r** [comment]
thank u
