### ISSUE TITLE
No downloads folder etc

### ISSUE THREAD

**Issue by JaidenCarew** [n0l3r/tiktok-downloader#12]
![nodownloads](https://user-images.githubusercontent.com/44959248/201499815-b2221894-fbb1-4e79-bf0b-0c46fc346475.PNG)
![downloads2](https://user-images.githubusercontent.com/44959248/201499819-968af367-476a-4e1b-98d8-d43575d7cffa.PNG)

**Comment by karim0sec** [comment]
just create folder with downloads name lol

**Comment by n0l3r** [comment]
you just need to create a new folder with the name "downloads". Now I have updated this repository. Please re-clone this repo
