### ISSUE TITLE
can get it a web with froms

### ISSUE THREAD

**Issue by 9804701373** [n0l3r/tiktok-downloader#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 9804701373** [comment]
<!DOCTYPE html>
<html lang = "en">
<head>
  <meta charset = "UTF-8">
  <link rel = "stylesheet" href="style.css">
  <title> My Form </title>
</head>
<body>
  <header>
    <h1>search-tiktok video</h1>
  </header>
  <form action="/search" method="POST">
    
      
      <label>Serch by username or link</label>
      <input type ="text" id = 'empID' placeholder="@username" name="id" required>
      
      
      <button type ="submit">Submit</button>
      <strong><button type ="reset">Reset</button></strong>
  </form>
  </body>

**Comment by n0l3r** [comment]
You mean ?

**Comment by 9804701373** [comment]
post via usrname fetch list
