### ISSUE TITLE
Only 30 videos found

### ISSUE THREAD

**Issue by tbm** [n0l3r/tiktok-downloader#19]
**Describe the bug**
It says `30 video found` but there are more videos. I picked `Mass Download (Username)` and `Without Watermark`.

**Expected behavior**
Download all videos.

This is with latest code from GitHub. I tested with different TikTok accounts - always limited to 30 videos.

**Comment by n0l3r** [comment]
I haven't had time to make a TikTok captcha bypass yet. So I made the browser visible, and you can fill in the captchas manually

**Comment by tbm** [comment]
> So I made the browser visible,

Sorry, is this documented somewhere?  I don't know how this works.

**Comment by n0l3r** [comment]
clone this repository again, then do it as usual. Then you will see a browser appear. If there is a request to fill in the captcha, fill in the captcha quickly. Because you only have a few seconds before the program terminates with an error.

If you have successfully filled in the captcha, the program will run normally.

Let me know if you find another error

**Comment by tbm** [comment]
Oh, I didn't do `git pull`.

I get the browser now...  I did 2 captchas but I still only get 30 downloads.

At the end I get:

```
[*] URL: https://www.tiktok.com/XXXXXXXXXXXXXXXXXX
[+] Downloaded successfully

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'downloads/72XXXXXXXXXXXXXXX.mp4'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'downloads/72XXXXXXXXXXXXXXXXXXXXXXX.mp4'
}

Node.js v18.13.0
```

**Comment by n0l3r** [comment]
reclone this repo sir

**Comment by tbm** [comment]
I have the latest version:

```
[*] Total video found: 30
[!] Found 30 video
[*] Downloading video 1 of 30
...
[*] Downloading video 30 of 30
[*] URL: https://www.tiktok.com/.......
[+] Downloaded successfully
```

The error is gone but it's still limited to 30.

**Comment by tbm** [comment]
I wonder if this is a timing issues because sometimes it finds all videos and sometimes only 30.
