### ISSUE TITLE
The program only finds 30 videos...

### ISSUE THREAD

**Issue by Nemeziz** [n0l3r/tiktok-downloader#2]
The program only finds 30 videos...

Test with the user @yelp

![image](https://user-images.githubusercontent.com/4735142/172644502-991b8018-b5b1-4241-ae1a-f4deb007a13f.png)

**Comment by n0l3r** [comment]
try changing the headless code: true to false on line 111. try to see the process, make sure the internet network is good

**Comment by n0l3r** [comment]
![image](https://user-images.githubusercontent.com/71002775/172929120-174774cc-b337-4428-b43e-ebca45daf197.png)

**Comment by Maximapple** [comment]
> try changing the headless code: true to false on line 111. try to see the process, make sure the internet network is good

tried this too, it still only finds 30. the page isn't loading any more videos for some reason. got any suggestions on how to fix this?
