### ISSUE TITLE
Issue 29

### ISSUE THREAD

**Issue by Keytoll** [n0l3r/tiktok-downloader#29]
i did this, videos are now found but im getting |Error: URL not found|

_Originally posted by @duchieu235 in https://github.com/n0l3r/tiktok-downloader/issues/25#issuecomment-1586624568_

**Comment by GiaoThay** [comment]
> ```
>           i did this, videos are now found but im getting |Error: URL not found|
> ```
> 
> _Originally posted by @duchieu235 in [#25 (comment)](https://github.com/n0l3r/tiktok-downloader/issues/25#issuecomment-1586624568)_

tiktok khoá link trong thẻ a rồi ông ơi . ".tiktok-1s72ajp-DivWrapper > a"

**Comment by Alexo88** [comment]
same

**Comment by TranNgocKhoa** [comment]
Found this useful tool: https://apify.com/novi/fast-tiktok-api

**Comment by Alexo88** [comment]
> 

isnt free
