### ISSUE TITLE
List of URLs

### ISSUE THREAD

**Issue by Maximapple** [n0l3r/tiktok-downloader#3]
Hi,

Could you please implement a feature where we can create a text file called 'urls' (in the directory of the script) and then the script downloads all the videos that are listed there?

Would appreciate it :)

Thanks,
Maxim

**Comment by tempus099** [comment]
Hi! Has this feature been added? It would be EXTREMELY helpful. Thanks!! :)

**Comment by n0l3r** [comment]
Hi! I have updated this repository. Please re-clone this repo
