### ISSUE TITLE
0 videos found

### ISSUE THREAD

**Issue by akshaypkbhat** [n0l3r/tiktok-downloader#32]
0 videos found after no watermark > chromium opened > channel opened > 0 videos found in terminal, then program closes.

I was using the program for multiple weeks recently, have had this problem. TikTok have patched a loophole?

**Comment by Alexo88** [comment]
same problem

**Comment by TranNgocKhoa** [comment]
Found this useful tool: https://apify.com/novi/fast-tiktok-api

**Comment by Zebraslive** [comment]
@akshaypkbhat @Alexo88 @TranNgocKhoa I've fixed the problem and created a pull request.

just use the updated version here until my pull is merged https://github.com/Zebraslive/tiktok-downloader

**Comment by frozenpandaman** [comment]
@Zebraslive Doesn't seem to be working.
