### ISSUE TITLE
Deleted videos error is confusing

### ISSUE THREAD

**Issue by tbm** [n0l3r/tiktok-downloader#42]
Commit 39852e9ac0c8b09c10ebdbec3aab2cdcba12d7d1 introduced a message that I don't find very useful - especially since I choose the "Single Download" option:

```
? Choose a option Single Download (URL)
? Choose a option Without Watermark
? Enter the URL :  ...
[!] Found 1 video
[*] Downloading video 1 of 1
[*] URL: ...
[!] 0 of 1 videos were deleted!
[+] Downloaded successfully
```

Would it make sense to print this line only if a video was actually deleted or something?

CC @Schmidii99

**Comment by NeonGamerBot-QK** [comment]
#43  fixes this
