### ISSUE TITLE
Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by tbm** [n0l3r/tiktok-downloader#50]
**Describe the bug**
I get an error when downloading a single video.

```
[*] URL: https://www.tiktok.com/@.....
Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideo (/home/tbm/src/tiktok-downloader/index.js:126:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/tbm/src/tiktok-downloader/index.js:320:20
Response body: 
/home/tbm/src/tiktok-downloader/index.js:133
    if (res.aweme_list[0].aweme_id != idVideo) {
            ^

TypeError: Cannot read properties of undefined (reading 'aweme_list')
    at getVideo (/home/tbm/src/tiktok-downloader/index.js:133:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/tbm/src/tiktok-downloader/index.js:320:20

Node.js v18.19.0
```
I get this error when downloading a video: Single download, without watermark.

It happens on every single video I tried.  It was working fine a few days ago.

Can you reproduce this issue?

**Comment by DD7-13** [comment]
Seems like a server error, so the easy fix for me is to change `useast1a` to `useast2a` here:
` const API_URL = `https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=${idVideo}`;`

**Comment by jgore077** [comment]
@DD7-13 This fix worked but how did you know to change that line?

**Comment by DD7-13** [comment]
> @DD7-13 This fix worked but how did you know to change that line?
I don't know, actually. I just tried to change the server name and it worked. After that I tried a few other possible names, but no luck

**Comment by timmbobb** [comment]
So does this repo work then? and any beginner info in how to get it setup?

**Comment by jgore077** [comment]
@timmbobb Are you talking in very general terms, do you know git clone and npm i or are you referring to how certain parts of the repo are broken when you first clone it?

**Comment by timmbobb** [comment]
I actually figured it out. Got the part where the server wasn't working or
region or whatever.

**Comment by jgore077** [comment]
I think the entire repo just broke and yt-dlp is also broken.

**Comment by iddogino** [comment]
Getting the same issue now... Tried switching between a handful of server URLs (useast1a, useast2a, useast5) with no luck... Anyone ran into this before?

**Comment by jgore077** [comment]
Its changing frequently now with the U.S tiktok ban but even yt-dlp doesnt have the new url yet.

**Comment by jgore077** [comment]
@tdevly Can you show how the url is formed on [line 124](https://github.com/n0l3r/tiktok-downloader/blob/265506741d5d489f19fca8657c6a74ad9a006fa2/index.js#L124) because I replace my url to 

```
const API_URL = `https:/api31-normal-probe-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=${idVideo}`;
```
but I am still getting the error that @tbm had.

**Comment by jgore077** [comment]
@tdevly I can confirm that this doesnt work as a replacement but what method did you obtain this api endpoint?

**Comment by sarevok89** [comment]
I have exactly the same issue as you guys. I tried checking multiple combinations of API numbers and regions using a for loop but none of them worked. Did you find any working API URL?

**Comment by timmbobb** [comment]
I think we should at least add some error handling here so that it's more understandable what's going on when this happens. A "Incorrect API endpoint" error would be much more helpful, and more accurate then what is currently displayed when this happens.

**Comment by Pinaka1289** [comment]
I tried all the above suggestions still no luck.. having the same issue

**Comment by Laiteux** [comment]
Tried bruteforcing every domain in that list, found some that worked but upon sending a second request they stop working. Not sure if it's just random or anything, but it definitely seems like no matter the domain you'll find, the `/aweme/v1/feed` endpoint is being deprecated by TikTok and will stop working anyway. Seems like a whole new solution is required.

**Comment by Sunda001** [comment]
> Did the job for everyone here and tried bruteforcing every domain in that list. Found some that worked but upon sending a second request they stop returning JSON.
> 
> Not sure if it's just random (probably) or anything, but it definitely seems like no matter the "working domain" you'll find, the `/aweme/v1/feed` endpoint is being deprecated by TikTok and will stop working anyway.
> 
> Seems like a whole new solution is required. Some downloader bots still seem to work, not sure what's their approach.
> 
> RIP `/aweme/v1/feed`.
> 
> <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/33204743/316186003-da56d5c6-774e-4402-8165-53de8496e101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIwMzgsIm5iZiI6MTcxMTMxMTczOCwicGF0aCI6Ii8zMzIwNDc0My8zMTYxODYwMDMtZGE1NmQ1YzYtNzc0ZS00NDAyLTgxNjUtNTNkZTg0OTZlMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiM2QyZWFmODc5ZDdlOTQ0YTk3ZjE1MjMzOTY4YzRmYjRiMDk0YWEyZWQ0ZjYxZTkwOWFiZWY2NGJjODc0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pNOLqnGQ5uZbbVsQ9yPlx4siH2wtsNm3OsjKCe90qmo"> <img alt="image" width="857" src="https://private-user-images.githubusercontent.com/33204743/316186251-49c65c68-0e71-4e8f-95f5-ffbf404ce92d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIwMzgsIm5iZiI6MTcxMTMxMTczOCwicGF0aCI6Ii8zMzIwNDc0My8zMTYxODYyNTEtNDljNjVjNjgtMGU3MS00ZThmLTk1ZjUtZmZiZjQwNGNlOTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjkyZWNmNGU4NmQ3MWI2MjFmNzcwZTI4NzljOWMxMTkxOGNmODFmNTI3Y2EwYTA2ZjM3YTAyNDAzNmYyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fqv4II6XPGhAHBn-iHfLwk45byxTMvmKRXm881QSWWQ">

they use mobile private API which requires special headers

**Comment by timmbobb** [comment]
> > Did the job for everyone here and tried bruteforcing every domain in that list. Found some that worked but upon sending a second request they stop returning JSON.
> > Not sure if it's just random (probably) or anything, but it definitely seems like no matter the "working domain" you'll find, the `/aweme/v1/feed` endpoint is being deprecated by TikTok and will stop working anyway.
> > Seems like a whole new solution is required. Some downloader bots still seem to work, not sure what's their approach.
> > RIP `/aweme/v1/feed`.
> > <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/33204743/316186003-da56d5c6-774e-4402-8165-53de8496e101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIwMzgsIm5iZiI6MTcxMTMxMTczOCwicGF0aCI6Ii8zMzIwNDc0My8zMTYxODYwMDMtZGE1NmQ1YzYtNzc0ZS00NDAyLTgxNjUtNTNkZTg0OTZlMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiM2QyZWFmODc5ZDdlOTQ0YTk3ZjE1MjMzOTY4YzRmYjRiMDk0YWEyZWQ0ZjYxZTkwOWFiZWY2NGJjODc0MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pNOLqnGQ5uZbbVsQ9yPlx4siH2wtsNm3OsjKCe90qmo"> <img alt="image" width="857" src="https://private-user-images.githubusercontent.com/33204743/316186251-49c65c68-0e71-4e8f-95f5-ffbf404ce92d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTIwMzgsIm5iZiI6MTcxMTMxMTczOCwicGF0aCI6Ii8zMzIwNDc0My8zMTYxODYyNTEtNDljNjVjNjgtMGU3MS00ZThmLTk1ZjUtZmZiZjQwNGNlOTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYjkyZWNmNGU4NmQ3MWI2MjFmNzcwZTI4NzljOWMxMTkxOGNmODFmNTI3Y2EwYTA2ZjM3YTAyNDAzNmYyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fqv4II6XPGhAHBn-iHfLwk45byxTMvmKRXm881QSWWQ">
> 
> they use mobile private API which requires special headers

Do you have any idea on how to implement this???

**Comment by jgore077** [comment]
I found a working repo [here ](https://github.com/sheldygg/aiotiktok). This is the endpoint its using `"https://api22-normal-c-alisg.tiktokv.com/"`

**Comment by timmbobb** [comment]
> > Well, I have a pull request waiting to be accepted that allows people to deploy this to google cloud, and it works currently. Pull request just needs to be accepted. It's also a little bit more of an involved setup than just using the command line though. Still free which is nice.
> 
> It looks your using the old api endpoint, is this right?

Not using any of our endpoints at all. Look in the server.js of the pull request.

**Comment by n0l3r** [comment]
check latest version please

**Comment by MichaelT-178** [comment]
It's not working again. Same issue as of May 17th.
