### ISSUE TITLE
Invalid API endpoint issues.

### ISSUE THREAD

**Issue by MichaelT-178** [n0l3r/tiktok-downloader#65]
**Describe the bug**
I get the following output 
```
TypeError: Cannot read properties of undefined (reading 'aweme_list')
    at getVideo (Users/name/tiktok-downloader/index.js:142:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/name/tiktok-downloader/index.js:235:20

Node.js v18.17.0
```

**Expected behavior**
It's supposed to download the video

**Comment by Jettcodey** [comment]
Hey this Problem should be Solved now, pls try again by git Clone/ Downloading the Latest version of the repository

**Comment by MichaelT-178** [comment]
It works again! Thank you so much!

**Comment by mor-bitstar-sangtv** [comment]
Hi @Jettcodey, how do you find information about the methods of this API? Can you share with me?

**Comment by Jettcodey** [comment]
@mor-bitstar-sangtv  I'm just experimenting with the API using educated guesses or by packet sniffing my smartphones while using the app. Nothing really special, I would say.

**Comment by TranNgocKhoa** [comment]
I think the author can not maintain this tool. It's better to use my example tool for better stable. It can extract many other data also: https://github.com/TranNgocKhoa/tiktok-crawler-python
