### ISSUE TITLE
Response body: ratelimit triggered

### ISSUE THREAD

**Issue by skcin7** [n0l3r/tiktok-downloader#68]
**Describe the bug**
I keep getting a "Response body: ratelimit triggered" error when downloading, which causes the script to crash.

Any idea how to fix?

**Comment by ashrefrb** [comment]
any fixes yet ?

**Comment by vcongtrinh** [comment]
i also got this error

**Comment by alexhochreiter** [comment]
Has this issue been resolved?
```
Error parsing JSON: SyntaxError: Unexpected token 'r', "ratelimit triggered" is not valid JSON
    at JSON.parse (<anonymous>)
    at getVideo (/Users/alex/tmp/tiktok-downloader/cli/index.js:171:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/alex/tmp/tiktok-downloader/cli/index.js:396:18
Response body: ratelimit triggered
Rate limit triggered. Logging URL to retry.txt
```

Edit: just found out that this only happens with vm.tiktok urls. Let the web browser resolve the url and use the resulting url with the cli and everything works great.
